# -------------------------------------------------------
# BASIC SETTINGS
# -------------------------------------------------------
server.port=8888
spring.application.name=api-gateway

# -------------------------------------------------------
# LOGGING - JSON logs (console only)
# logback-spring.xml handles JSON formatting
# -------------------------------------------------------
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.rhf.gateway=INFO

# Optional fallback log pattern (only applies if JSON encoder is disabled)
logging.pattern.console=%d{ISO8601} %-5level [%X{correlationId:-}] %logger - %msg%n


# -------------------------------------------------------
# GATEWAY: DEFAULT FILTERS
# - CorrelationId: inject & propagate X-Correlation-Id
# - SimpleRateLimiter: small token bucket (per IP or API key)
# -------------------------------------------------------
spring.cloud.gateway.default-filters[0]=CorrelationId

spring.cloud.gateway.default-filters[1].name=SimpleRateLimiter
spring.cloud.gateway.default-filters[1].args.replenishPerSecond=1
spring.cloud.gateway.default-filters[1].args.burstCapacity=2
spring.cloud.gateway.default-filters[1].args.keyHeader=X-Api-Key


# -------------------------------------------------------
# GATEWAY ROUTES
#Only exposes the services that  external clients need.
#Internal service-to-service calls do NOT need to go through the gateway hence driver service is not configured here
# -------------------------------------------------------
# Trip Service
spring.cloud.gateway.routes[0].id=trip_service
spring.cloud.gateway.routes[0].uri=http://trip-service:9082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/trips/**

# Rider Service
spring.cloud.gateway.routes[1].id=rider_service
spring.cloud.gateway.routes[1].uri=http://rider-service:9081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/riders/**

# Payment Service
spring.cloud.gateway.routes[2].id=payment_service
spring.cloud.gateway.routes[2].uri=http://payment-service:9083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/payments/**

