# -------------------------------------------------------
# BASIC SETTINGS
# -------------------------------------------------------
server.port=8888
spring.application.name=api-gateway

# -------------------------------------------------------
# LOGGING
# -------------------------------------------------------
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.rhf.gateway=INFO
logging.pattern.console=%d{ISO8601} %-5level [%X{correlationId:-}] %logger - %msg%n

# -------------------------------------------------------
# DEFAULT FILTERS
# -------------------------------------------------------
spring.cloud.gateway.default-filters[0]=CorrelationId

spring.cloud.gateway.default-filters[1].name=SimpleRateLimiter
spring.cloud.gateway.default-filters[1].args.replenishPerSecond=1
spring.cloud.gateway.default-filters[1].args.burstCapacity=2
spring.cloud.gateway.default-filters[1].args.keyHeader=X-Api-Key


# -------------------------------------------------------
# TRIP SERVICE
# Incoming:   /api/trips/**
# Backend:    /v1/trips/**
# -------------------------------------------------------
spring.cloud.gateway.routes[0].id=trip_service
spring.cloud.gateway.routes[0].uri=http://host.docker.internal:9082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/trips/**
spring.cloud.gateway.routes[0].filters[0].name=RewritePath
spring.cloud.gateway.routes[0].filters[0].args.regexp=/api/trips(?<segment>/?.*)
spring.cloud.gateway.routes[0].filters[0].args.replacement=/v1/trips${segment}


# -------------------------------------------------------
# RIDER SERVICE
# Incoming:   /api/riders/**
# Backend:    /v1/riders/**
# -------------------------------------------------------
spring.cloud.gateway.routes[1].id=rider_service
spring.cloud.gateway.routes[1].uri=http://host.docker.internal:9081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/riders/**
spring.cloud.gateway.routes[1].filters[0].name=RewritePath
spring.cloud.gateway.routes[1].filters[0].args.regexp=/api/riders(?<segment>/?.*)
spring.cloud.gateway.routes[1].filters[0].args.replacement=/v1/riders${segment}


# -------------------------------------------------------
# PAYMENT SERVICE
# Incoming:   /api/payments/**
# Backend:    /v1/payments/**
# -------------------------------------------------------
spring.cloud.gateway.routes[2].id=payment_service
spring.cloud.gateway.routes[2].uri=http://host.docker.internal:9083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[2].filters[0].name=RewritePath
spring.cloud.gateway.routes[2].filters[0].args.regexp=/api/payments(?<segment>/?.*)
spring.cloud.gateway.routes[2].filters[0].args.replacement=/v1/payments${segment}
